### ISSUE TITLE
请问可以修改汉化的脚本么？

### ISSUE THREAD

**Issue by sdfsddf33322d** [AyamiKaze/AI6WIN_Script_Tool#1]
这是媚肉之香的

https://github.com/TesterTesterov/AI6WINScriptTool/files/8338873/mes.zip

**Comment by AyamiKaze** [comment]
理论上可以，稍微改一下就可以，不过我没测试。
话说你解中文文本干什么？

**Comment by sdfsddf33322d** [comment]
主要是在学习日语的过程中发现有些翻译不得体可能会造成对剧情有重大误解的地方有些在意，想自己修正一下作为保存的版本，好像是gb2312的。不知道会不会很麻烦，可有偿。

**Comment by sdfsddf33322d** [comment]
> 理论上可以，稍微改一下就可以，不过我没测试。 话说你解中文文本干什么？

主要是在学习日语的过程中发现有些翻译不得体可能会造成对剧情有重大误解的地方有些在意，想自己修正一下作为保存的版本，好像是gb2312的。不知道会不会很麻烦，可有偿。

**Comment by AyamiKaze** [comment]
> > 理论上可以，稍微改一下就可以，不过我没测试。 话说你解中文文本干什么？
> 
> 主要是在学习日语的过程中发现有些翻译不得体可能会造成对剧情有重大误解的地方有些在意，想自己修正一下作为保存的版本，好像是gb2312的。不知道会不会很麻烦，可有偿。

2889624807，这是我的qq，如果有需要可以联系。
ps：最近有点忙，可能回复比较晚。
